function [A,H] = clc_AH_gyropode_TP_V2(tb,tm,vb,vm,MR,IR,RR,MB,IB,LB,Mbat,Ibat,Lbat,Im,G)
%CLC_AH_GYROPODE_TP_V2
%    [A,H] = CLC_AH_GYROPODE_TP_V2(TB,TM,VB,VM,MR,IR,RR,MB,IB,LB,MBAT,IBAT,LBAT,IM,G)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Mar-2022 09:06:20

t2 = RR.^2;
t3 = cos(tb);
t4 = MB.*t2;
t5 = MR.*t2;
t6 = Mbat.*t2;
A = reshape([IB+IR+Ibat+t4+t5+t6+LB.^2.*MB+Lbat.^2.*Mbat+LB.*MB.*RR.*t3.*2.0+Lbat.*Mbat.*RR.*t3.*2.0,IR+t5+MB.*RR.*(RR+LB.*t3)+Mbat.*RR.*(RR+Lbat.*t3),IR+t4+t5+t6+LB.*MB.*RR.*t3+Lbat.*Mbat.*RR.*t3,IR+Im+t4+t5+t6],[2,2]);
if nargout > 1
    t7 = sin(tb);
    t8 = vb.^2;
    H = [-G.*LB.*MB.*t7-G.*Lbat.*Mbat.*t7-LB.*MB.*RR.*t7.*t8-Lbat.*Mbat.*RR.*t7.*t8;-vb.*(LB.*MB.*RR.*t7.*vb+Lbat.*Mbat.*RR.*t7.*vb)];
end
