function [A,H] = clc_AH_gyropode_TP(in1,in2,in3)
%CLC_AH_GYROPODE_TP
%    [A,H] = CLC_AH_GYROPODE_TP(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    02-Mar-2022 21:41:11

G = in3(:,11);
IB = in3(:,5);
IR = in3(:,2);
Im = in3(:,10);
LB = in3(:,6);
Lbat = in3(:,9);
MB = in3(:,4);
MR = in3(:,1);
Mbat = in3(:,7);
RR = in3(:,3);
tb = in1(2,:);
vb = in2(2,:);
t2 = cos(tb);
t3 = sin(tb);
t4 = RR.^2;
t5 = vb.^2;
t6 = MB.*t4;
t7 = MR.*t4;
t8 = Mbat.*t4;
A = reshape([IR+Im+t6+t7+t8,IR+t6+t7+t8+LB.*MB.*RR.*t2+Lbat.*Mbat.*RR.*t2,IR+t7+MB.*RR.*(RR+LB.*t2)+Mbat.*RR.*(RR+Lbat.*t2),IB+IR+t6+t7+t8+LB.^2.*MB+Lbat.^2.*Mbat+LB.*MB.*RR.*t2.*2.0+Lbat.*Mbat.*RR.*t2.*2.0],[2,2]);
if nargout > 1
    H = [-vb.*(LB.*MB.*RR.*t3.*vb+Lbat.*Mbat.*RR.*t3.*vb);-G.*LB.*MB.*t3-G.*Lbat.*Mbat.*t3-LB.*MB.*RR.*t3.*t5-Lbat.*Mbat.*RR.*t3.*t5];
end
